name: Deploy PHP App

on:
    push:
        branches:
            - main
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Perform system check on remote server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      command -v php > /dev/null || { echo "PHP is not installed"; exit 1; }
                      command -v apache2 > /dev/null || { echo "Apache2 is not installed"; exit 1; }
                      systemctl is-active --quiet apache2 || { echo "Apache2 is not running"; exit 1; }

            - name: Copy code to remote server
              uses: appleboy/scp-action@master
              with:
                  source: "."
                  target: "/tmp/deploy"
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy code to /var/www/html
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      sudo rsync -av --delete /tmp/deploy/ /var/www/html/
                      sudo chown -R www-data:www-data /var/www/html/
                      sudo find /var/www/html/ -type d -exec chmod 755 {} \;
                      sudo find /var/www/html/ -type f -exec chmod 644 {} \;

            - name: Restart apache2 service on remote server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: sudo systemctl restart apache2

            - name: Confirm deployment
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: curl -I http://127.0.0.1/server-status | grep "200 OK" || { echo "Deployment failed"; exit 1; }
