name: Deploy Blood-Bank-And-Donation-Management-System

on:
    push:
        branches:
            - main
            - master

jobs:
    system-check:
        runs-on: ubuntu-latest

        steps:
            - name: Perform system check on remote server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      command -v php > /dev/null || { echo "PHP is not installed"; exit 1; }
                      command -v apache2 > /dev/null || { echo "Apache2 is not installed"; exit 1; }
                      systemctl is-active --quiet apache2 || { echo "Apache2 is not running"; exit 1; }
                      
                      echo "Check if UFW is active..."
                      if sudo ufw status | grep -q "Status: active"; then
                        echo "UFW is active"
                      else
                        echo "UFW is not active"
                        exit 1
                      fi
                      
                      echo "Check if the domain blood.nguyenphucthuan.id.vn is reachable and has SSL enabled..."
                      if curl -Is https://blood.nguyenphucthuan.id.vn | grep -q "200 OK"; then
                        echo "Domain is reachable and SSL is enabled"
                      else
                        echo "Domain is not reachable or SSL is not enabled"
                        exit 1
                      fi
                      
                      echo "Check disk space usage..."
                      if df -h | grep '^/dev/' | awk '{ if ($5+0 > 80) exit 1 }'; then
                        echo "Disk space usage is within limits"
                      else
                        echo "Disk space usage is too high"
                        exit 1
                      fi
                      echo "All infrastructure checks passed successfully."
    check-database-connection:
        runs-on: ubuntu-latest

        steps:
            - name: Check if database is reachable
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      echo "Checking if database is reachable..."
                      if nc -zv ${{ secrets.DATABASE_IP }} ${{ secrets.DATABASE_PORT }}; then
                        echo "Database is reachable"
                      else
                        echo "Database is not reachable"
                        exit 1
                      fi
                      
    copy-code:
        runs-on: ubuntu-latest
        needs: [system-check, check-database-connection]

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Copy code to remote server
              uses: appleboy/scp-action@master
              with:
                  source: "."
                  target: "/tmp/deploy"
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}

    deploy-code:
        runs-on: ubuntu-latest
        needs: copy-code

        steps:
            - name: Deploy code to /var/www/html
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      sudo rsync -av --delete /tmp/deploy/ /var/www/html/
                      sudo chown -R www-data:www-data /var/www/html/
                      sudo find /var/www/html/ -type d -exec chmod 755 {} \;
                      sudo find /var/www/html/ -type f -exec chmod 644 {} \;

    restart-apache:
        runs-on: ubuntu-latest
        needs: deploy-code

        steps:
            - name: Restart apache2 service on remote server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: sudo systemctl restart apache2

            - name: Remove unnecessary files and folder
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                   sudo rm -rf /var/www/html/sql/
                   sudo rm -rf /var/www/html/.git/
                   sudo rm -rf /var/www/html/.github/
                   sudo rm -rf /var/www/html.gitignores/

    confirm-deployment:
        runs-on: ubuntu-latest
        needs: restart-apache

        steps:
            - name: Confirm deployment
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: curl -I http://127.0.0.1/server-status | grep "200 OK" || { echo "Deployment failed"; exit 1; }
